export const mock = [
    {
        effective_date: "2023-01-01",
        pdf_url : "www.pdfurl.com",
        xml_ur: "www.xlrUrl.com",
        number: "12",
        property: "Eko Home Club",
        description: "Aluguel",
        behavior: "charge_tenand",
        value: 1000,
        paid_at: "2023-01-01",
    },
    {
        effective_date: "2023-01-01",
        pdf_url : "www.pdfurl.com",
        xml_ur: "www.xlrUrl.com",
        number: "43",
        property: "Eko Home Club",
        description: "Aluguel",
        behavior: "charge_tenand",
        value: 4000,
        paid_at: "2023-01-01",
    },
    {
        effective_date: "2023-01-01",
        pdf_url : "www.pdfurl.com",
        xml_ur: "www.xlrUrl.com",
        number: "10",
        property: "Eko Home Club",
        description: "Aluguel",
        behavior: "charge_tenand",
        value: 5000,
        paid_at: "2023-01-01",
    },
    {
        effective_date: "2023-01-01",
        pdf_url : "www.pdfurl.com",
        xml_ur: "www.xlrUrl.com",
        number: "12",
        property: "Eko Home Club",
        description: "Aluguel",
        behavior: "charge_tenand",
        value: 1000,
        paid_at: "2023-01-01",
    },
    {
        effective_date: "2023-01-03",
        pdf_url : "www.pdfurl.com",
        xml_ur: "www.xlrUrl.com",
        number: "43",
        property: "Eko Home Club",
        description: "Aluguel",
        behavior: "charge_tenand",
        value: 4000,
        paid_at: "2023-01-01",
    },
    {
        effective_date: "2023-01-03",
        pdf_url : "www.pdfurl.com",
        xml_ur: "www.xlrUrl.com",
        number: "10",
        property: "Eko Home Club",
        description: "Aluguel",
        behavior: "charge_tenand",
        value: 5000,
        paid_at: "2023-01-01",
    }
]